//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
 * Copyright The Kubernetes Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by conversion-gen. DO NOT EDIT.

package v1

import (
	unsafe "unsafe"

	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	types "k8s.io/apimachinery/pkg/types"
	checkpoint "sigs.k8s.io/dra-example-driver/internal/api/checkpoint"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*Checkpoint)(nil), (*checkpoint.Checkpoint)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Checkpoint_To_checkpoint_Checkpoint(a.(*Checkpoint), b.(*checkpoint.Checkpoint), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*checkpoint.Checkpoint)(nil), (*Checkpoint)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_checkpoint_Checkpoint_To_v1_Checkpoint(a.(*checkpoint.Checkpoint), b.(*Checkpoint), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PreparedClaim)(nil), (*checkpoint.PreparedClaim)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_PreparedClaim_To_checkpoint_PreparedClaim(a.(*PreparedClaim), b.(*checkpoint.PreparedClaim), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*checkpoint.PreparedClaim)(nil), (*PreparedClaim)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_checkpoint_PreparedClaim_To_v1_PreparedClaim(a.(*checkpoint.PreparedClaim), b.(*PreparedClaim), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1_Checkpoint_To_checkpoint_Checkpoint(in *Checkpoint, out *checkpoint.Checkpoint, s conversion.Scope) error {
	out.PreparedClaims = *(*[]checkpoint.PreparedClaim)(unsafe.Pointer(&in.PreparedClaims))
	return nil
}

// Convert_v1_Checkpoint_To_checkpoint_Checkpoint is an autogenerated conversion function.
func Convert_v1_Checkpoint_To_checkpoint_Checkpoint(in *Checkpoint, out *checkpoint.Checkpoint, s conversion.Scope) error {
	return autoConvert_v1_Checkpoint_To_checkpoint_Checkpoint(in, out, s)
}

func autoConvert_checkpoint_Checkpoint_To_v1_Checkpoint(in *checkpoint.Checkpoint, out *Checkpoint, s conversion.Scope) error {
	out.PreparedClaims = *(*[]PreparedClaim)(unsafe.Pointer(&in.PreparedClaims))
	return nil
}

// Convert_checkpoint_Checkpoint_To_v1_Checkpoint is an autogenerated conversion function.
func Convert_checkpoint_Checkpoint_To_v1_Checkpoint(in *checkpoint.Checkpoint, out *Checkpoint, s conversion.Scope) error {
	return autoConvert_checkpoint_Checkpoint_To_v1_Checkpoint(in, out, s)
}

func autoConvert_v1_PreparedClaim_To_checkpoint_PreparedClaim(in *PreparedClaim, out *checkpoint.PreparedClaim, s conversion.Scope) error {
	out.UID = types.UID(in.UID)
	return nil
}

// Convert_v1_PreparedClaim_To_checkpoint_PreparedClaim is an autogenerated conversion function.
func Convert_v1_PreparedClaim_To_checkpoint_PreparedClaim(in *PreparedClaim, out *checkpoint.PreparedClaim, s conversion.Scope) error {
	return autoConvert_v1_PreparedClaim_To_checkpoint_PreparedClaim(in, out, s)
}

func autoConvert_checkpoint_PreparedClaim_To_v1_PreparedClaim(in *checkpoint.PreparedClaim, out *PreparedClaim, s conversion.Scope) error {
	out.UID = types.UID(in.UID)
	return nil
}

// Convert_checkpoint_PreparedClaim_To_v1_PreparedClaim is an autogenerated conversion function.
func Convert_checkpoint_PreparedClaim_To_v1_PreparedClaim(in *checkpoint.PreparedClaim, out *PreparedClaim, s conversion.Scope) error {
	return autoConvert_checkpoint_PreparedClaim_To_v1_PreparedClaim(in, out, s)
}
