//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
 * Copyright The Kubernetes Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	fs "io/fs"
	unsafe "unsafe"

	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	types "k8s.io/apimachinery/pkg/types"
	checkpoint "sigs.k8s.io/dra-example-driver/internal/api/checkpoint"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*Checkpoint)(nil), (*checkpoint.Checkpoint)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Checkpoint_To_checkpoint_Checkpoint(a.(*Checkpoint), b.(*checkpoint.Checkpoint), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*checkpoint.Checkpoint)(nil), (*Checkpoint)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_checkpoint_Checkpoint_To_v1alpha1_Checkpoint(a.(*checkpoint.Checkpoint), b.(*Checkpoint), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ContainerEdits)(nil), (*checkpoint.ContainerEdits)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ContainerEdits_To_checkpoint_ContainerEdits(a.(*ContainerEdits), b.(*checkpoint.ContainerEdits), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*checkpoint.ContainerEdits)(nil), (*ContainerEdits)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_checkpoint_ContainerEdits_To_v1alpha1_ContainerEdits(a.(*checkpoint.ContainerEdits), b.(*ContainerEdits), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Device)(nil), (*checkpoint.Device)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Device_To_checkpoint_Device(a.(*Device), b.(*checkpoint.Device), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*checkpoint.Device)(nil), (*Device)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_checkpoint_Device_To_v1alpha1_Device(a.(*checkpoint.Device), b.(*Device), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DeviceNode)(nil), (*checkpoint.DeviceNode)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DeviceNode_To_checkpoint_DeviceNode(a.(*DeviceNode), b.(*checkpoint.DeviceNode), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*checkpoint.DeviceNode)(nil), (*DeviceNode)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_checkpoint_DeviceNode_To_v1alpha1_DeviceNode(a.(*checkpoint.DeviceNode), b.(*DeviceNode), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Hook)(nil), (*checkpoint.Hook)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Hook_To_checkpoint_Hook(a.(*Hook), b.(*checkpoint.Hook), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*checkpoint.Hook)(nil), (*Hook)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_checkpoint_Hook_To_v1alpha1_Hook(a.(*checkpoint.Hook), b.(*Hook), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*IntelRdt)(nil), (*checkpoint.IntelRdt)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_IntelRdt_To_checkpoint_IntelRdt(a.(*IntelRdt), b.(*checkpoint.IntelRdt), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*checkpoint.IntelRdt)(nil), (*IntelRdt)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_checkpoint_IntelRdt_To_v1alpha1_IntelRdt(a.(*checkpoint.IntelRdt), b.(*IntelRdt), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Mount)(nil), (*checkpoint.Mount)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Mount_To_checkpoint_Mount(a.(*Mount), b.(*checkpoint.Mount), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*checkpoint.Mount)(nil), (*Mount)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_checkpoint_Mount_To_v1alpha1_Mount(a.(*checkpoint.Mount), b.(*Mount), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PreparedClaim)(nil), (*checkpoint.PreparedClaim)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PreparedClaim_To_checkpoint_PreparedClaim(a.(*PreparedClaim), b.(*checkpoint.PreparedClaim), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*checkpoint.PreparedClaim)(nil), (*PreparedClaim)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_checkpoint_PreparedClaim_To_v1alpha1_PreparedClaim(a.(*checkpoint.PreparedClaim), b.(*PreparedClaim), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PreparedDevice)(nil), (*checkpoint.PreparedDevice)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PreparedDevice_To_checkpoint_PreparedDevice(a.(*PreparedDevice), b.(*checkpoint.PreparedDevice), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*checkpoint.PreparedDevice)(nil), (*PreparedDevice)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_checkpoint_PreparedDevice_To_v1alpha1_PreparedDevice(a.(*checkpoint.PreparedDevice), b.(*PreparedDevice), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_Checkpoint_To_checkpoint_Checkpoint(in *Checkpoint, out *checkpoint.Checkpoint, s conversion.Scope) error {
	out.PreparedClaims = *(*map[types.UID]checkpoint.PreparedClaim)(unsafe.Pointer(&in.PreparedClaims))
	return nil
}

// Convert_v1alpha1_Checkpoint_To_checkpoint_Checkpoint is an autogenerated conversion function.
func Convert_v1alpha1_Checkpoint_To_checkpoint_Checkpoint(in *Checkpoint, out *checkpoint.Checkpoint, s conversion.Scope) error {
	return autoConvert_v1alpha1_Checkpoint_To_checkpoint_Checkpoint(in, out, s)
}

func autoConvert_checkpoint_Checkpoint_To_v1alpha1_Checkpoint(in *checkpoint.Checkpoint, out *Checkpoint, s conversion.Scope) error {
	out.PreparedClaims = *(*map[types.UID]PreparedClaim)(unsafe.Pointer(&in.PreparedClaims))
	return nil
}

// Convert_checkpoint_Checkpoint_To_v1alpha1_Checkpoint is an autogenerated conversion function.
func Convert_checkpoint_Checkpoint_To_v1alpha1_Checkpoint(in *checkpoint.Checkpoint, out *Checkpoint, s conversion.Scope) error {
	return autoConvert_checkpoint_Checkpoint_To_v1alpha1_Checkpoint(in, out, s)
}

func autoConvert_v1alpha1_ContainerEdits_To_checkpoint_ContainerEdits(in *ContainerEdits, out *checkpoint.ContainerEdits, s conversion.Scope) error {
	out.Env = *(*[]string)(unsafe.Pointer(&in.Env))
	out.DeviceNodes = *(*[]*checkpoint.DeviceNode)(unsafe.Pointer(&in.DeviceNodes))
	out.Hooks = *(*[]*checkpoint.Hook)(unsafe.Pointer(&in.Hooks))
	out.Mounts = *(*[]*checkpoint.Mount)(unsafe.Pointer(&in.Mounts))
	out.IntelRdt = (*checkpoint.IntelRdt)(unsafe.Pointer(in.IntelRdt))
	out.AdditionalGIDs = *(*[]uint32)(unsafe.Pointer(&in.AdditionalGIDs))
	return nil
}

// Convert_v1alpha1_ContainerEdits_To_checkpoint_ContainerEdits is an autogenerated conversion function.
func Convert_v1alpha1_ContainerEdits_To_checkpoint_ContainerEdits(in *ContainerEdits, out *checkpoint.ContainerEdits, s conversion.Scope) error {
	return autoConvert_v1alpha1_ContainerEdits_To_checkpoint_ContainerEdits(in, out, s)
}

func autoConvert_checkpoint_ContainerEdits_To_v1alpha1_ContainerEdits(in *checkpoint.ContainerEdits, out *ContainerEdits, s conversion.Scope) error {
	out.Env = *(*[]string)(unsafe.Pointer(&in.Env))
	out.DeviceNodes = *(*[]*DeviceNode)(unsafe.Pointer(&in.DeviceNodes))
	out.Hooks = *(*[]*Hook)(unsafe.Pointer(&in.Hooks))
	out.Mounts = *(*[]*Mount)(unsafe.Pointer(&in.Mounts))
	out.IntelRdt = (*IntelRdt)(unsafe.Pointer(in.IntelRdt))
	out.AdditionalGIDs = *(*[]uint32)(unsafe.Pointer(&in.AdditionalGIDs))
	return nil
}

// Convert_checkpoint_ContainerEdits_To_v1alpha1_ContainerEdits is an autogenerated conversion function.
func Convert_checkpoint_ContainerEdits_To_v1alpha1_ContainerEdits(in *checkpoint.ContainerEdits, out *ContainerEdits, s conversion.Scope) error {
	return autoConvert_checkpoint_ContainerEdits_To_v1alpha1_ContainerEdits(in, out, s)
}

func autoConvert_v1alpha1_Device_To_checkpoint_Device(in *Device, out *checkpoint.Device, s conversion.Scope) error {
	out.RequestNames = *(*[]string)(unsafe.Pointer(&in.RequestNames))
	out.PoolName = in.PoolName
	out.DeviceName = in.DeviceName
	out.CdiDeviceIds = *(*[]string)(unsafe.Pointer(&in.CdiDeviceIds))
	return nil
}

// Convert_v1alpha1_Device_To_checkpoint_Device is an autogenerated conversion function.
func Convert_v1alpha1_Device_To_checkpoint_Device(in *Device, out *checkpoint.Device, s conversion.Scope) error {
	return autoConvert_v1alpha1_Device_To_checkpoint_Device(in, out, s)
}

func autoConvert_checkpoint_Device_To_v1alpha1_Device(in *checkpoint.Device, out *Device, s conversion.Scope) error {
	out.RequestNames = *(*[]string)(unsafe.Pointer(&in.RequestNames))
	out.PoolName = in.PoolName
	out.DeviceName = in.DeviceName
	out.CdiDeviceIds = *(*[]string)(unsafe.Pointer(&in.CdiDeviceIds))
	return nil
}

// Convert_checkpoint_Device_To_v1alpha1_Device is an autogenerated conversion function.
func Convert_checkpoint_Device_To_v1alpha1_Device(in *checkpoint.Device, out *Device, s conversion.Scope) error {
	return autoConvert_checkpoint_Device_To_v1alpha1_Device(in, out, s)
}

func autoConvert_v1alpha1_DeviceNode_To_checkpoint_DeviceNode(in *DeviceNode, out *checkpoint.DeviceNode, s conversion.Scope) error {
	out.Path = in.Path
	out.HostPath = in.HostPath
	out.Type = in.Type
	out.Major = in.Major
	out.Minor = in.Minor
	out.FileMode = (*fs.FileMode)(unsafe.Pointer(in.FileMode))
	out.Permissions = in.Permissions
	out.UID = (*uint32)(unsafe.Pointer(in.UID))
	out.GID = (*uint32)(unsafe.Pointer(in.GID))
	return nil
}

// Convert_v1alpha1_DeviceNode_To_checkpoint_DeviceNode is an autogenerated conversion function.
func Convert_v1alpha1_DeviceNode_To_checkpoint_DeviceNode(in *DeviceNode, out *checkpoint.DeviceNode, s conversion.Scope) error {
	return autoConvert_v1alpha1_DeviceNode_To_checkpoint_DeviceNode(in, out, s)
}

func autoConvert_checkpoint_DeviceNode_To_v1alpha1_DeviceNode(in *checkpoint.DeviceNode, out *DeviceNode, s conversion.Scope) error {
	out.Path = in.Path
	out.HostPath = in.HostPath
	out.Type = in.Type
	out.Major = in.Major
	out.Minor = in.Minor
	out.FileMode = (*fs.FileMode)(unsafe.Pointer(in.FileMode))
	out.Permissions = in.Permissions
	out.UID = (*uint32)(unsafe.Pointer(in.UID))
	out.GID = (*uint32)(unsafe.Pointer(in.GID))
	return nil
}

// Convert_checkpoint_DeviceNode_To_v1alpha1_DeviceNode is an autogenerated conversion function.
func Convert_checkpoint_DeviceNode_To_v1alpha1_DeviceNode(in *checkpoint.DeviceNode, out *DeviceNode, s conversion.Scope) error {
	return autoConvert_checkpoint_DeviceNode_To_v1alpha1_DeviceNode(in, out, s)
}

func autoConvert_v1alpha1_Hook_To_checkpoint_Hook(in *Hook, out *checkpoint.Hook, s conversion.Scope) error {
	out.HookName = in.HookName
	out.Path = in.Path
	out.Args = *(*[]string)(unsafe.Pointer(&in.Args))
	out.Env = *(*[]string)(unsafe.Pointer(&in.Env))
	out.Timeout = (*int)(unsafe.Pointer(in.Timeout))
	return nil
}

// Convert_v1alpha1_Hook_To_checkpoint_Hook is an autogenerated conversion function.
func Convert_v1alpha1_Hook_To_checkpoint_Hook(in *Hook, out *checkpoint.Hook, s conversion.Scope) error {
	return autoConvert_v1alpha1_Hook_To_checkpoint_Hook(in, out, s)
}

func autoConvert_checkpoint_Hook_To_v1alpha1_Hook(in *checkpoint.Hook, out *Hook, s conversion.Scope) error {
	out.HookName = in.HookName
	out.Path = in.Path
	out.Args = *(*[]string)(unsafe.Pointer(&in.Args))
	out.Env = *(*[]string)(unsafe.Pointer(&in.Env))
	out.Timeout = (*int)(unsafe.Pointer(in.Timeout))
	return nil
}

// Convert_checkpoint_Hook_To_v1alpha1_Hook is an autogenerated conversion function.
func Convert_checkpoint_Hook_To_v1alpha1_Hook(in *checkpoint.Hook, out *Hook, s conversion.Scope) error {
	return autoConvert_checkpoint_Hook_To_v1alpha1_Hook(in, out, s)
}

func autoConvert_v1alpha1_IntelRdt_To_checkpoint_IntelRdt(in *IntelRdt, out *checkpoint.IntelRdt, s conversion.Scope) error {
	out.ClosID = in.ClosID
	out.L3CacheSchema = in.L3CacheSchema
	out.MemBwSchema = in.MemBwSchema
	out.EnableCMT = in.EnableCMT
	out.EnableMBM = in.EnableMBM
	return nil
}

// Convert_v1alpha1_IntelRdt_To_checkpoint_IntelRdt is an autogenerated conversion function.
func Convert_v1alpha1_IntelRdt_To_checkpoint_IntelRdt(in *IntelRdt, out *checkpoint.IntelRdt, s conversion.Scope) error {
	return autoConvert_v1alpha1_IntelRdt_To_checkpoint_IntelRdt(in, out, s)
}

func autoConvert_checkpoint_IntelRdt_To_v1alpha1_IntelRdt(in *checkpoint.IntelRdt, out *IntelRdt, s conversion.Scope) error {
	out.ClosID = in.ClosID
	out.L3CacheSchema = in.L3CacheSchema
	out.MemBwSchema = in.MemBwSchema
	out.EnableCMT = in.EnableCMT
	out.EnableMBM = in.EnableMBM
	return nil
}

// Convert_checkpoint_IntelRdt_To_v1alpha1_IntelRdt is an autogenerated conversion function.
func Convert_checkpoint_IntelRdt_To_v1alpha1_IntelRdt(in *checkpoint.IntelRdt, out *IntelRdt, s conversion.Scope) error {
	return autoConvert_checkpoint_IntelRdt_To_v1alpha1_IntelRdt(in, out, s)
}

func autoConvert_v1alpha1_Mount_To_checkpoint_Mount(in *Mount, out *checkpoint.Mount, s conversion.Scope) error {
	out.HostPath = in.HostPath
	out.ContainerPath = in.ContainerPath
	out.Options = *(*[]string)(unsafe.Pointer(&in.Options))
	out.Type = in.Type
	return nil
}

// Convert_v1alpha1_Mount_To_checkpoint_Mount is an autogenerated conversion function.
func Convert_v1alpha1_Mount_To_checkpoint_Mount(in *Mount, out *checkpoint.Mount, s conversion.Scope) error {
	return autoConvert_v1alpha1_Mount_To_checkpoint_Mount(in, out, s)
}

func autoConvert_checkpoint_Mount_To_v1alpha1_Mount(in *checkpoint.Mount, out *Mount, s conversion.Scope) error {
	out.HostPath = in.HostPath
	out.ContainerPath = in.ContainerPath
	out.Options = *(*[]string)(unsafe.Pointer(&in.Options))
	out.Type = in.Type
	return nil
}

// Convert_checkpoint_Mount_To_v1alpha1_Mount is an autogenerated conversion function.
func Convert_checkpoint_Mount_To_v1alpha1_Mount(in *checkpoint.Mount, out *Mount, s conversion.Scope) error {
	return autoConvert_checkpoint_Mount_To_v1alpha1_Mount(in, out, s)
}

func autoConvert_v1alpha1_PreparedClaim_To_checkpoint_PreparedClaim(in *PreparedClaim, out *checkpoint.PreparedClaim, s conversion.Scope) error {
	out.PreparedDevices = *(*[]checkpoint.PreparedDevice)(unsafe.Pointer(&in.PreparedDevices))
	return nil
}

// Convert_v1alpha1_PreparedClaim_To_checkpoint_PreparedClaim is an autogenerated conversion function.
func Convert_v1alpha1_PreparedClaim_To_checkpoint_PreparedClaim(in *PreparedClaim, out *checkpoint.PreparedClaim, s conversion.Scope) error {
	return autoConvert_v1alpha1_PreparedClaim_To_checkpoint_PreparedClaim(in, out, s)
}

func autoConvert_checkpoint_PreparedClaim_To_v1alpha1_PreparedClaim(in *checkpoint.PreparedClaim, out *PreparedClaim, s conversion.Scope) error {
	out.PreparedDevices = *(*[]PreparedDevice)(unsafe.Pointer(&in.PreparedDevices))
	return nil
}

// Convert_checkpoint_PreparedClaim_To_v1alpha1_PreparedClaim is an autogenerated conversion function.
func Convert_checkpoint_PreparedClaim_To_v1alpha1_PreparedClaim(in *checkpoint.PreparedClaim, out *PreparedClaim, s conversion.Scope) error {
	return autoConvert_checkpoint_PreparedClaim_To_v1alpha1_PreparedClaim(in, out, s)
}

func autoConvert_v1alpha1_PreparedDevice_To_checkpoint_PreparedDevice(in *PreparedDevice, out *checkpoint.PreparedDevice, s conversion.Scope) error {
	if err := Convert_v1alpha1_Device_To_checkpoint_Device(&in.Device, &out.Device, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ContainerEdits_To_checkpoint_ContainerEdits(&in.ContainerEdits, &out.ContainerEdits, s); err != nil {
		return err
	}
	out.AdminAccess = in.AdminAccess
	return nil
}

// Convert_v1alpha1_PreparedDevice_To_checkpoint_PreparedDevice is an autogenerated conversion function.
func Convert_v1alpha1_PreparedDevice_To_checkpoint_PreparedDevice(in *PreparedDevice, out *checkpoint.PreparedDevice, s conversion.Scope) error {
	return autoConvert_v1alpha1_PreparedDevice_To_checkpoint_PreparedDevice(in, out, s)
}

func autoConvert_checkpoint_PreparedDevice_To_v1alpha1_PreparedDevice(in *checkpoint.PreparedDevice, out *PreparedDevice, s conversion.Scope) error {
	if err := Convert_checkpoint_Device_To_v1alpha1_Device(&in.Device, &out.Device, s); err != nil {
		return err
	}
	if err := Convert_checkpoint_ContainerEdits_To_v1alpha1_ContainerEdits(&in.ContainerEdits, &out.ContainerEdits, s); err != nil {
		return err
	}
	out.AdminAccess = in.AdminAccess
	return nil
}

// Convert_checkpoint_PreparedDevice_To_v1alpha1_PreparedDevice is an autogenerated conversion function.
func Convert_checkpoint_PreparedDevice_To_v1alpha1_PreparedDevice(in *checkpoint.PreparedDevice, out *PreparedDevice, s conversion.Scope) error {
	return autoConvert_checkpoint_PreparedDevice_To_v1alpha1_PreparedDevice(in, out, s)
}
