# please keep this alphabetized
version: "2"
run:
  tests: true
linters:
  enable:
    - asciicheck
    - contextcheck
    - forcetypeassert
    - gocritic
    - godot
    - misspell
    - staticcheck
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - sigs.k8s.io/dra-example-driver
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
