# This pod will be evicted by once the device taint rule is created
apiVersion: v1
kind: Pod
metadata:
  namespace: basic-resourceclaimtemplate
  name: pod-to-be-evicted
  labels:
    app: pod-to-be-evicted
spec:
  containers:
  - name: ctr0
    image: ubuntu:22.04
    command: ["bash", "-c"]
    args: ["export; trap 'exit 0' TERM; sleep 9999 & wait"]
    resources:
      claims:
      - name: gpu
  resourceClaims:
  - name: gpu
    resourceClaimTemplateName: single-gpu