./cp_pod_node.sh ../tools/dlv
./cp_pod_node.sh ../tools/dlv_client
./cp_pod_node.sh ../tools/npc
./cp_pod_node.sh ../tools/kube-scheduler
./cp_pod_node.sh ./start_debug.sh
./cp_pod_node.sh ./kill_process.sh
./cp_pod_node.sh ./enable_schedule.sh
./cp_pod_node.sh ./show_ps.sh
./cp_pod_node.sh ./disable_schedule.sh
