---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "rasberrypi-pico-driver.fullname" . }}-kubeletplugin
  namespace: {{ include "rasberrypi-pico-driver.namespace" . }}
  labels:
    {{- include "rasberrypi-pico-driver.labels" . | nindent 4 }}
    app.kubernetes.io/component: kubeletplugin
spec:
  selector:
    matchLabels:
      {{- include "rasberrypi-pico-driver.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: kubeletplugin
  {{- with .Values.kubeletPlugin.updateStrategy }}
  updateStrategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.kubeletPlugin.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "rasberrypi-pico-driver.templateLabels" . | nindent 8 }}
        app.kubernetes.io/component: kubeletplugin
    spec:
      {{- if .Values.kubeletPlugin.priorityClassName }}
      priorityClassName: {{ .Values.kubeletPlugin.priorityClassName }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "rasberrypi-pico-driver.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.kubeletPlugin.podSecurityContext | nindent 8 }}
      containers:
      - name: plugin
        securityContext:
          {{- toYaml .Values.kubeletPlugin.containers.plugin.securityContext | nindent 10 }}
        image: {{ include "rasberrypi-pico-driver.fullimage" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["rasberrypi-pico-kubeletplugin"]
        resources:
          {{- toYaml .Values.kubeletPlugin.containers.plugin.resources | nindent 10 }}
        env:
        - name: CDI_ROOT
          value: /var/run/cdi
        - name: KUBELET_REGISTRAR_DIRECTORY_PATH
          value: {{ .Values.kubeletPlugin.kubeletRegistrarDirectoryPath | quote }}
        - name: KUBELET_PLUGINS_DIRECTORY_PATH
          value: {{ .Values.kubeletPlugin.kubeletPluginsDirectoryPath | quote }}
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        # Simulated number of devices the example driver will pretend to have.
        - name: VENDOR_ID
          value: "2e8a"
        volumeMounts:
        - name: plugins-registry
          mountPath: {{ .Values.kubeletPlugin.kubeletRegistrarDirectoryPath | quote }}
        - name: plugins
          mountPath: {{ .Values.kubeletPlugin.kubeletPluginsDirectoryPath | quote }}
        - name: cdi
          mountPath: /var/run/cdi
        - name: udev
          mountPath: /run/udev
        - name: usb
          mountPath: /dev/bus/usb
        - name: dev
          mountPath: /dev
      volumes:
      - name: dev
        hostPath:
          path: /dev
      - name: udev
        hostPath:
          path: /run/udev
      - name: usb
        hostPath:
          path: /dev/bus/usb
      - name: plugins-registry
        hostPath:
          path: {{ .Values.kubeletPlugin.kubeletRegistrarDirectoryPath | quote }}
      - name: plugins
        hostPath:
          path: {{ .Values.kubeletPlugin.kubeletPluginsDirectoryPath | quote }}
      - name: cdi
        hostPath:
          path: /var/run/cdi
      {{- with .Values.kubeletPlugin.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kubeletPlugin.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kubeletPlugin.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
