{{- if .Values.webhook.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "rasberrypi-pico-driver.fullname" . }}-webhook-cert
  namespace: {{ include "rasberrypi-pico-driver.namespace" . }}
  labels:
    {{- include "rasberrypi-pico-driver.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
spec:
  dnsNames:
    {{- $svcName := printf "%s-webhook" (include "rasberrypi-pico-driver.fullname" .) }}
    {{- $svcNamespace := (include "rasberrypi-pico-driver.namespace" .) }}
    - {{ $svcName }}.{{ $svcNamespace }}.svc
  issuerRef:
    kind: Issuer
    name: {{ include "rasberrypi-pico-driver.fullname" . }}-webhook-issuer
  secretName: {{ include "rasberrypi-pico-driver.fullname" . }}-webhook-cert
{{- end }}
