# Example: Shared GPU Across Containers
#
# One pod, two containers.
# Each asking for shared access to a single GPU.
#
# Expected: Both containers see the same GPU. Check with:
#   kubectl logs -n basic-shared-claim-across-containers pod0 -c ctr0 | grep GPU_DEVICE
#   kubectl logs -n basic-shared-claim-across-containers pod0 -c ctr1 | grep GPU_DEVICE
# Both containers should show the same GPU ID.
#
# Driver requirements:
#   Profile: gpu
#   GPUs: 1
#
# Cluster requirements:
#   Kubernetes 1.34+

---
apiVersion: v1
kind: Namespace
metadata:
  name: basic-shared-claim-across-containers

---
apiVersion: resource.k8s.io/v1
kind: ResourceClaimTemplate
metadata:
  namespace: basic-shared-claim-across-containers
  name: single-gpu
spec:
  spec:
    devices:
      requests:
      - name: gpu
        exactly:
          deviceClassName: gpu.example.com

---
apiVersion: v1
kind: Pod
metadata:
  namespace: basic-shared-claim-across-containers
  name: pod0
spec:
  containers:
  - name: ctr0
    image: ubuntu:22.04
    command: ["bash", "-c"]
    args: ["export; trap 'exit 0' TERM; sleep 9999 & wait"]
    resources:
      claims:
      - name: shared-gpu
  - name: ctr1
    image: ubuntu:22.04
    command: ["bash", "-c"]
    args: ["export; trap 'exit 0' TERM; sleep 9999 & wait"]
    resources:
      claims:
      - name: shared-gpu
  resourceClaims:
  - name: shared-gpu
    resourceClaimTemplateName: single-gpu
