# One shared, global claim providing access to a GPU
# Two pods, each asking for access to the shared GPU

---
apiVersion: v1
kind: Namespace
metadata:
  name: gpu-test4

---
apiVersion: resource.k8s.io/v1beta1
kind: ResourceClaim
metadata:
  namespace: gpu-test4
  name: single-gpu
spec:
  devices:
    requests:
    - name: gpu
      deviceClassName: rasberrypi.pico.com

---
apiVersion: v1
kind: Pod
metadata:
  namespace: gpu-test4
  name: pod0
  labels:
    app: pod
spec:
  containers:
  - name: ctr0
    image: mpremote:latest
    imagePullPolicy: Never
    command: ["bash", "-c"]
    args: ["while true; do mpremote run status.py; sleep 1; done"]
    resources:
      claims:
      - name: shared-gpu
  resourceClaims:
  - name: shared-gpu
    resourceClaimName: single-gpu

---
apiVersion: v1
kind: Pod
metadata:
  namespace: gpu-test4
  name: pod1
  labels:
    app: pod
spec:
  containers:
  - name: ctr0
    image: mpremote:latest
    imagePullPolicy: Never
    command: ["bash", "-c"]
    args: ["while true; do mpremote run status.py; sleep 1; done"]
    resources:
      claims:
      - name: shared-gpu
  resourceClaims:
  - name: shared-gpu
    resourceClaimName: single-gpu
