# One Namespace with admin access label
# One pod with one container requesting all GPUs with admin access
# This demo shows the DRA admin access feature with DRA_ADMIN_ACCESS environment variable

---
apiVersion: v1
kind: Namespace
metadata:
  name: gpu-test7
  labels:
    resource.kubernetes.io/admin-access: "true"
---
apiVersion: resource.k8s.io/v1
kind: ResourceClaimTemplate
metadata:
  namespace: gpu-test7
  name: multiple-gpus-admin
spec:
  spec: 
    devices:
      requests:
      - name: admin-gpu
        exactly:
          deviceClassName: gpu.example.com
          allocationMode: All
          adminAccess: true

---
apiVersion: v1
kind: Pod
metadata:
  namespace: gpu-test7
  name: pod0
spec:
  containers:
  - name: ctr0
    image: ubuntu:22.04
    command: ["bash", "-c"]
    args:
    - |
      export
      echo "=== DRA Admin Access Demo ==="
      echo "DRA Admin Access: $DRA_ADMIN_ACCESS"
      echo ""
      echo "GPU Environment Variables:"
      env | grep GPU_ | sort
      echo ""
      echo "=== Sleeping to allow inspection ==="
      trap 'exit 0' TERM
      sleep 9999 & wait
    resources:
      claims:
      - name: admin-gpus
  resourceClaims:
  - name: admin-gpus
    resourceClaimTemplateName: multiple-gpus-admin
