# One pod, one container
# Asking for 2 distinct Npus

---
apiVersion: v1
kind: Namespace
metadata:
  name: npu-test2

---
apiVersion: resource.k8s.io/v1beta1
kind: ResourceClaimTemplate
metadata:
  namespace: npu-test2
  name: multiple-npus
spec:
  spec:
    devices:
      requests:
      - name: npus
        deviceClassName: npu.example.com
        allocationMode: ExactCount
        count: 2

---
apiVersion: v1
kind: Pod
metadata:
  namespace: npu-test2
  name: pod0
  labels:
    app: pod
spec:
  containers:
  - name: ctr0
    image: ubuntu:22.04
    command: ["bash", "-c"]
    args: ["export; trap 'exit 0' TERM; sleep 9999 & wait"]
    resources:
      claims:
      - name: npus
  resourceClaims:
  - name: npus
    resourceClaimTemplateName: multiple-npus
