# One pod, 1 container
# Run as deployment with 1 replica

---
apiVersion: v1
kind: Namespace
metadata:
  name: npu-test5

---
apiVersion: resource.k8s.io/v1beta1
kind: ResourceClaimTemplate
metadata:
  namespace: npu-test5
  name: multiple-npus
spec:
  spec:
    devices:
      requests:
      - name: ts-npu
        deviceClassName: npu.example.com
      - name: sp-npu
        deviceClassName: npu.example.com
      config:
      - requests: ["ts-npu"]
        opaque:
          driver: npu.example.com
          parameters:
            apiVersion: npu.resource.example.com/v1alpha1
            kind: NpuConfig
            sharing:
              strategy: TimeSlicing
              timeSlicingConfig:
                interval: Long
      - requests: ["sp-npu"]
        opaque:
          driver: npu.example.com
          parameters:
            apiVersion: npu.resource.example.com/v1alpha1
            kind: NpuConfig
            sharing:
              strategy: SpacePartitioning
              spacePartitioningConfig:
                partitionCount: 10

---
apiVersion: v1
kind: Pod
metadata:
  namespace: npu-test5
  name: pod0
spec:
  containers:
  - name: ts-ctr0
    image: ubuntu:22.04
    command: ["bash", "-c"]
    args: ["export; trap 'exit 0' TERM; sleep 9999 & wait"]
    resources:
      claims:
      - name: shared-npus
        request: ts-npu
  - name: ts-ctr1
    image: ubuntu:22.04
    command: ["bash", "-c"]
    args: ["export; trap 'exit 0' TERM; sleep 9999 & wait"]
    resources:
      claims:
      - name: shared-npus
        request: ts-npu
  - name: sp-ctr0
    image: ubuntu:22.04
    command: ["bash", "-c"]
    args: ["export; trap 'exit 0' TERM; sleep 9999 & wait"]
    resources:
      claims:
      - name: shared-npus
        request: sp-npu
  - name: sp-ctr1
    image: ubuntu:22.04
    command: ["bash", "-c"]
    args: ["export; trap 'exit 0' TERM; sleep 9999 & wait"]
    resources:
      claims:
      - name: shared-npus
        request: sp-npu
  resourceClaims:
  - name: shared-npus
    resourceClaimTemplateName: multiple-npus
