name: Run tests

on: [ push, pull_request ]

permissions:
  contents: read

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.24.2
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Build
      run: make PREFIX=artifacts cmds
    - name: install helm and kubectl
      run: |
        sudo snap install helm --classic
        sudo snap install kubectl --classic
    - name: install kind
      run: |
        go install sigs.k8s.io/kind@v0.27.0
    - name: Setup e2e
      run: make setup-e2e
    - name: run e2e test
      run: make test-e2e
    - name: teardown e2e test
      run: make teardown-e2e 
