name: Run lint

on: [ push, pull_request ]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Install Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version-file: hack/tools/golangci-lint/go.mod
    - name: Get golangci-lint version
      id: linter-version
      run: |
        go -C hack/tools/golangci-lint list -m -f 'version={{.Version}}' github.com/golangci/golangci-lint/v2 >> "$GITHUB_OUTPUT"
    - name: Lint
      uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
      with:
        version: ${{ steps.linter-version.outputs.version }}
        args: -v --timeout 5m --build-tags=e2e ./...
        skip-cache: true
